Хендлер "Регенерация пригласительной ссылки"
training-of-new-employees/qon pull request #101
Opened 2024-01-14 18:28 UTC by Orendev

2024-01-14 19:51 UTC, kozyrev-m requested changes

2024-01-14 19:51 UTC, kozyrev-m commented on internal/app/rest/handlers.go
> +	invitationLinkGroup.Use(s.IsAuthenticated())
Здесь ещё можно добавить middleware для проверки роли "Админ" - s.IsAdmin()

2024-01-14 19:51 UTC, kozyrev-m commented on internal/app/rest/user_handler.go
> +	if !access.CanAdmin(session.IsAdmin, session.UserID, userAdmin.ID) {
Если будет добавлен middleware s.IsAdmin(), то можно будет убрать эту проверку.

Получается можно убрать весь код со строчки 464-478

2024-01-14 19:51 UTC, kozyrev-m commented on internal/model/invitation_link.go
> +	return validation.ValidateStruct(c,
Предлагаю немного изменить реализацию.

За образец можно взять валидатор `func (u *UserCreate) Validation() error` из [файла model/user.go
](https://github.com/training-of-new-employees/qon/blob/v1-regenerate-invitation-link/internal/model/user.go)
Здесь при нарушении требований валидации возвращаются зарегистрированные ошибки приложения. Для емейла будет errs.ErrEmailNotEmpty, errs.ErrInvalidEmail.

Такой подход позволит корректно обрабатывать ошибки.

2024-01-14 19:51 UTC, kozyrev-m commented on internal/app/rest/user_handler_test.go
> +		isAdmin      bool
Если будет добавлен middleware s.IsAdmin(), то можно будет убрать эту проверку.

2024-01-14 19:51 UTC, kozyrev-m commented on internal/app/rest/user_handler.go
> +	case errors.Is(err, errs.ErrUserNotFound):
Эту ошибку не нужно проверять, в handleError данная ошибка преобразовывается в код 404 и тело ответа с соответствующим текстом.

2024-01-14 19:51 UTC, kozyrev-m commented on internal/app/rest/user_handler.go
> +	invitationLinkResponse.Email = invitationLinkRequest.Email
В текущей реализации приложения Верхний уровень хендлеров отвечает за взаимодействие с внешним миром и преобразование запросов и ответов. А также за определение сценария работы приложения.

За бизнес логику уже отвечает слой сервис (service).

Т.е. здесь должен быть только один метод сервиса. Поэтому всю бизнес логику нужно перенести в отдельной метод сервиса.

Т.е. Бизнес-логика, которая находится в строках с 480 по 501, должна быть перенесена в отдельный метод на уровне сервиса.
Вся эта логика должна быть в методе r.services.User().RegenerationInvitationLinkUser.

2024-01-15 18:55 UTC, Orendev commented on internal/app/rest/user_handler_test.go
> +		isAdmin      bool
оставил это поле, есть сценарий где использую

2024-01-15 20:58 UTC, kozyrev-m approved these changes

2024-01-16 03:46 UTC, merged