V1 edit user
training-of-new-employees/qon pull request #121
Opened 2024-01-19 09:54 UTC by Nexadis

2024-01-19 10:12 UTC, kozyrev-m requested changes

2024-01-19 10:12 UTC, kozyrev-m commented on internal/app/rest/user_handler.go
> +		r.handleError(c, errs.ErrBadRequest)
Здесь лучше обрабатывать ошибку, которую получаем из edit.Validation().
Там же у нас все ошибки описаны и зарегистрированы в [rest/errs.go](https://github.com/training-of-new-employees/qon/blob/e294896140779cbf40cc4a7130541ef049703dd9/internal/app/rest/errs.go#L14)

2024-01-19 10:12 UTC, kozyrev-m commented on internal/service/impl/user_service_test.go
> +		{
Эти тесты лучше бы перенести в test suite.
Для примера, [position_service_test.go](https://github.com/training-of-new-employees/qon/blob/v1-get-invitation-link/internal/service/impl/position_service_test.go#L12)

_Планируется постепенно все тесты уровня сервиса перенести в test suite._

2024-01-19 11:35 UTC, Nexadis commented on internal/app/rest/user_handler.go
> +		r.handleError(c, errs.ErrBadRequest)
Сделал по примеру в других валидаций

2024-01-19 11:55 UTC, kozyrev-m commented on internal/app/rest/user_handler.go
> +		r.handleError(c, errs.ErrBadRequest)
Здесь вот так лучше сделать: `r.handleError(c, err)`.
Тогда будет пользователю возвращаться более информативная ошибка, а не просто 'bad request'

2024-01-19 11:55 UTC, kozyrev-m commented on internal/service/impl/user_service_test.go
> +		{
Хорошо

2024-01-20 07:15 UTC, kozyrev-m approved these changes

2024-01-20 07:38 UTC, kozyrev-m requested changes

2024-01-20 07:38 UTC, kozyrev-m commented on internal/model/user.go
> +	if err := validation.Validate(&u.Patronymic, validation.Required); err != nil {
У нас же может быть сотрудник без отчества.

2024-01-20 10:05 UTC, kozyrev-m approved these changes

2024-01-20 12:10 UTC, merged