feat: get user lesson data
training-of-new-employees/qon pull request #135
Opened 2024-01-25 12:10 UTC by MowlCoder

2024-01-25 16:41 UTC, Nexadis requested changes

2024-01-25 16:41 UTC, Nexadis commented on internal/app/rest/lesson_handlers.go
> +//	@Failure	500		{object}	errResponse
Тут можно добавить еще одну строку:
```go
//
//	@Security	Bearer
//
```
Так сваггер будет автоматически подставлять заданный токен в запросы

2024-01-25 16:41 UTC, Nexadis commented on internal/service/impl/lesson_service.go
> +	courses, err := l.db.CourseStorage().UserCourses(ctx, userID)
Теперь это можно будет сделать через метод получения курса по id из service-слоя

2024-01-26 14:20 UTC, kozyrev-m commented
В метод [GetUserCoursesStatus](https://github.com/training-of-new-employees/qon/blob/v1-get-user-lesson/internal/store/pg/course_storage.go#L66) нужно добавить функцию [syncUserCourseProgressTx](https://github.com/training-of-new-employees/qon/blob/v1-get-user-lesson/internal/store/pg/transaction.go#L319C24-L319C48) для синхронизации результата уроков и курса, на всякий случай.

2024-01-26 17:55 UTC, kozyrev-m approved these changes

2024-01-26 18:21 UTC, Nexadis approved these changes

2024-01-26 18:58 UTC, merged