Swagger docs
training-of-new-employees/qon pull request #159
Opened 2024-02-27 06:08 UTC by Nexadis

2024-02-27 13:25 UTC, kozyrev-m reviewed
Сейчас у пользователей api-документации есть непонимание в использовании json-ов для POST, PATCH запросов.
Для этих запросов формируются json-ы из пакета моделей.
Однако не все поля, которые указаны в теле json нужно передавать в этих запросах.

Возможно на уровне хендлеров нужно описать новые структуры, из которых будут формироваться json-ы для документации.

2024-02-27 13:56 UTC, kozyrev-m reviewed
Необходимо все названия хендлеров привести в соотвествие с названиями из [документации (столбец _Название 
Синтаксис: Кто? Где? Что?_)](https://docs.google.com/spreadsheets/d/1ZWvi8P1JnzwL9JB4dsUycvP5G3szR3BTy9bw5jhJyUc/edit#gid=506572004)

2024-02-27 14:04 UTC, kozyrev-m requested changes

2024-02-27 14:04 UTC, kozyrev-m commented on internal/app/rest/user_handler.go
>  //	@Summary		Получение данные авторизованного пользователя
Необходимо все названия хендлеров привести в соотвествие с названиями из [документации (столбец _Название 
Синтаксис: Кто? Где? Что?_)](https://docs.google.com/spreadsheets/d/1ZWvi8P1JnzwL9JB4dsUycvP5G3szR3BTy9bw5jhJyUc/edit#gid=506572004)

2024-02-27 14:37 UTC, Nexadis commented
> Сейчас у пользователей api-документации есть непонимание с json-нами для POST, PATCH запросов. В документации для этих запросов формируются json-ы из пакета моделей. Однако не все поля, которые указаны в теле json, должны отображаться для запросов.
> 
> То есть, те структуры, которые у нас сейчас есть в пакете моделей не совсем подходят для api-документации. Возможно, на уровне хендлеров нужно описать новые структуры, из которых будут формироваться json-ы с подходящей структурой для документации.

В документации нет описания тела запросов и ответов. Для исправления всего этого надо не просто документацию подправить, а рефакторинг делать.

2024-02-27 14:38 UTC, Nexadis commented on internal/app/rest/user_handler.go
>  //	@Summary		Получение данные авторизованного пользователя
в Summary прописать то, что написано в столбце "Название"?

2024-02-29 14:06 UTC, kozyrev-m commented on internal/app/rest/user_handler.go
>  //	@Summary		Получение данные авторизованного пользователя
Да

2024-03-05 11:51 UTC, kozyrev-m requested changes

2024-03-05 11:51 UTC, kozyrev-m commented on internal/app/rest/requests.go
> +}
Эти же структуры не используются для операций с базой данных.
Зачем у структур есть тег db?

2024-03-05 13:48 UTC, Nexadis commented on internal/app/rest/requests.go
> +}
Просто копипастил

2024-03-09 15:38 UTC, kozyrev-m approved these changes

2024-03-09 15:39 UTC, merged