v1-admin-add-lesson-block
training-of-new-employees/qon pull request #178
Opened 2024-05-12 16:44 UTC by kozyrev-m

Пока только добавлен хендлер для создания блоков уроков. В процессе разработки соответствующий функционал на уровне сервиса и хранилища .

2024-05-21 12:37 UTC, Nexadis requested changes

2024-05-21 12:37 UTC, Nexadis commented on internal/app/rest/block_handlers.go
> +	block, err := r.services.Block().CreateBlock(
Может это всё лучше вместить в сервис для работы с уроками, у нас же это часть логики урока.

2024-05-21 12:37 UTC, Nexadis commented on internal/model/block.go
> +type Block struct {
Немного не нравится название Block, я думаю нам нужно либо разделить текст и прочие части блока и обращаться к ним через указатель, либо назвать структуру просто Text (с полем Value или Content). Также можно всё что относится к блокам вынести в отдельный пакет block.

2024-05-21 12:37 UTC, Nexadis commented on internal/model/block.go
> +	Number   int    `db:"number"    json:"number"`
Если это позиция блока в уроке, то думаю, что лучше подойдёт `offset` или `position`, т.к. из number не сразу понятно что имеется ввиду

2024-05-21 12:37 UTC, Nexadis commented on internal/model/block.go
> +func (b *Block) Validation() error {
Соответственно тут для Структуры Text будет своя валидация, а для других объектов своя, чтоб не делать всё в структуре Block

2024-05-21 12:37 UTC, Nexadis commented on internal/service/impl/block_service.go
> +func (bs *blockService) CreateBlock(ctx context.Context, block model.Block) (*model.Block, error) {
В концепции использования отдельной структуры для текста мы сможем делать блоки с разным контентом:
```go
func (bs *blockService) NewText(ctx context.Context, text block.Text) (*block.Block, error)
// либо
func (bs *blockService) NewText(ctx context.Context, text string, lessonID, offset int) (*block.Block,error)
```

2024-05-21 12:45 UTC, kozyrev-m commented on internal/model/block.go
> +	Number   int    `db:"number"    json:"number"`
Согласен, неудачное название. Также нужно поменять и названия столбцов в таблицах. Я про это тоже думал.

2024-05-21 13:05 UTC, kozyrev-m commented on internal/model/block.go
> +type Block struct {
Дело в том, что на многочисленных встречах мы согласовали именно такую модель. Я тоже считаю, что делать текст основопологающем содержанием блока неправильно. По мне текст так же должен быть просто аттачментом.
Но согласовали именно так как реализовано.

2024-05-21 13:09 UTC, kozyrev-m commented on internal/app/rest/block_handlers.go
> +	block, err := r.services.Block().CreateBlock(
Тоже так изначально думал. В итоге решил сделать отдельно, для удобства, потому что уроки слишком разрослись. У нас сейчас в уроках функционал как для админа так и для сотрудника.

2024-05-21 13:17 UTC, Nexadis commented on internal/model/block.go
> +type Block struct {
Не присутствовал на встречах, @Julia-Ishmuratova, подскажи аргументы в пользу такого решения, почему не может быть блока без текста? Не лучше ли привязывать к блоку разные виды контента. То есть блок знает в каком он уроке и на какой позиции в нём, а вот содержание, это уже отдельная сущность, например: текст, изображение, видео, тест и тд

2024-05-21 13:20 UTC, Nexadis commented on internal/app/rest/block_handlers.go
> +	block, err := r.services.Block().CreateBlock(
На этот счёт у меня тоже появились мысли, т.к. по функциональности проект еле похож на что-то применимое, а вот сложность его уже такая, что дорабатывать и вносить новый функционал крайне сложно, я пытаюсь прорефакторить проект, в первую очередь, чтоб было легче расширять функционал, а также делаю там логирование, для простого отслеживания всех запросов и действий пользователей

2024-05-22 18:29 UTC, Julia-Ishmuratova commented on internal/model/block.go
> +type Block struct {
1. это был бы еще один уровень в этой и так уже многоуровневой матрешке.
2. принимая такое решение исходили из согласованного макета и требований, по которым блока БЕЗ текста быть не может. 

@kozyrev-m @Nexadis надеюсь, ответила) если такая локига - блокер для дальнейшей разработки - давайте обсуждать

2024-05-22 20:28 UTC, kozyrev-m commented on internal/model/block.go
> +type Block struct {
@Nexadis @Julia-Ishmuratova 
Нет это не блокер. Так как согласовано тоже можно.

Моё мнение такое. Если у нас уже есть макеты и согласованные требования, давайте придерживаться выбранного пути. Мы и так потратили много времени на обсуждения, и не раз. Поэтому возвращаться к ним больше не хотелось бы. Так можно бесконечно долго.

Просто есть ещё интересные задач, которые хотелось реализовать в данном проекте. Лучше потратить время на эти задачи.

2024-05-25 14:03 UTC, Nexadis approved these changes

2024-05-27 18:19 UTC, merged