mvp-1-position-course
training-of-new-employees/qon pull request #35
Opened 2023-12-12 18:14 UTC by kartalenka7

Добавлен хэндлер присвоения курса к должности

2023-12-13 04:43 UTC, Nexadis reviewed
Думаю еще можно добавить проверку, что company_id у position такой же как и у user, который хочет назначить этот position на курс. Иначе у нас получится, что любой админ из другой фирмы может переназначать курсы для должностей не своей компании.

2023-12-13 04:43 UTC, Nexadis commented on internal/app/rest/handlers.go
> +	mvp.POST("/", s.handlerAssignCourse)
Может сделать эндпоинт внутри position роута, чтоб он был закрыт для доступа для всех, кроме админа?

2023-12-13 08:19 UTC, Nexadis requested changes
@kozyrev-m @maarehet  Как думаете, нужно ли прятать пользователя, если он архивирован или принимать решение уже выше в сервисе?

2023-12-13 08:19 UTC, Nexadis commented on internal/model/error.go
> +	ErrNoAuthorized       = errors.New("user not ")
Как будто не хватает описания

2023-12-13 08:19 UTC, Nexadis commented on internal/store/pg/position_storage.go
> +              WHERE id = $1 AND archived = false`
Думаешь не надо получать данные о должности, если она заархивирована?

2023-12-13 08:31 UTC, kartalenka7 commented on internal/store/pg/position_storage.go
> +              WHERE id = $1 AND archived = false`
А зачем к архивированной должности присваивать курс?

2023-12-13 08:32 UTC, kartalenka7 commented on internal/store/pg/position_storage.go
> +              WHERE id = $1 AND archived = false`
А зачем к архивированной должности присваивать курс?

2023-12-13 08:46 UTC, Nexadis commented on internal/store/pg/position_storage.go
> +              WHERE id = $1 AND archived = false`
Это функция хранилища ведь, она позволяет получить должность по ID, этот функционал может понадобиться не только для присваивания курса

2023-12-13 08:53 UTC, kozyrev-m commented on internal/model/error.go
> +	ErrNoAuthorized       = errors.New("user not ")
Это файл будет немного переопределён, когда сольём его в develop.
Поэтому можно это не трогать.

2023-12-13 08:58 UTC, kozyrev-m commented
У меня непонимание по новому способу документации ([internal/app/rest/docs/swagger.yaml](https://github.com/training-of-new-employees/qon/blob/mvp-1-position-course/internal/app/rest/docs/swagger.yaml)):
Как мы её согласуем с текущим форматом ([swagger-spec/api.yaml](https://github.com/training-of-new-employees/qon/blob/develop/swagger-spec/api.yaml))

2023-12-14 06:24 UTC, kozyrev-m requested changes
Убрать internal/app/rest/docs/, так как мы будем генерить документацию в [docs/](https://github.com/training-of-new-employees/qon/tree/develop/docs)

2023-12-15 07:36 UTC, kozyrev-m approved these changes

2023-12-15 07:50 UTC, Nexadis approved these changes

2023-12-15 07:51 UTC, merged