mvp-1-lesson
training-of-new-employees/qon pull request #51
Opened 2023-12-18 08:31 UTC by kartalenka7

Хэндлеры для работы с уроками

2023-12-22 05:28 UTC, Nexadis requested changes

2023-12-22 05:28 UTC, Nexadis commented on internal/app/rest/handlers.go
> +	adminGroup.POST("/lesson", s.handlerLessonCreate)
Думаю лучше выделить эти эндпоинты в отдельную группу и назвать её во множественном числе `lessons`

2023-12-22 05:28 UTC, Nexadis commented on internal/app/rest/lesson_handlers.go
> +//		@Produce	json
Надо добавить параметр для тела запроса, а то получается, что это post запрос с пустым телом согласно спецификации, а по факту мы ждем модель `LessonCreate`

2023-12-22 05:28 UTC, Nexadis commented on internal/app/rest/lesson_handlers.go
> +//	 	@Produce	json
Тут также добавить параметр для ожидаемого json'а

2023-12-22 05:28 UTC, Nexadis commented on internal/service/impl/lesson_service.go
> +	createdLesson, err := l.db.LessonStorage().CreateLessonDB(ctx,
не понимаю в чем смысле постфикса DB

2023-12-22 05:28 UTC, Nexadis commented on internal/store/pg/lesson_storage.go
> +	tx, err := l.db.Beginx()
Думаю тут имеет смысл вынести в отдельную функцию обвязку для обработки транзакций, как в UserStorage, это повысит читаемость

2023-12-22 05:28 UTC, Nexadis commented on internal/store/pg/lesson_storage.go
> +	query := `SELECT id
Если передавать параметры через указатели, то не нужно будет проверять пустое ли значение, т.к. при unmarshal'e из json'a будем получать nil, которые сконвертируются в NULL SQL. А уже NULL'ы можно обернуть в `COALESCE`, чтобы обновлять только те значения, которые были заданы.

2023-12-22 05:28 UTC, Nexadis commented on internal/store/pg/lesson_storage.go
> +	query := `SELECT id
Это не рекомендация к действию

2023-12-26 17:26 UTC, Nexadis commented on internal/app/rest/handlers.go
> +	adminGroup.GET("/lesson", s.handlerLessonGet)
Также не понятно как пользователь будет получать доступ к курсу, который ему назначили, если это доступно только админу

2023-12-28 08:17 UTC, kozyrev-m requested changes

2023-12-28 08:17 UTC, kozyrev-m commented on internal/store/pg/lesson_storage.go
> +	query := `SELECT id
Реализация метода UpdateLessonDB переусложнена. В дальнейшем это усложнит сопровождение и написание тестов для метода.

Лучше упростить. За основу можно взять реализацию UpdatePositionDB из develop.
Ограничиться можно одним запросом, пустые значения можно обрабатывать через `COALESCE`.

2023-12-28 11:59 UTC, kozyrev-m approved these changes

2023-12-28 15:39 UTC, Nexadis approved these changes

2023-12-28 17:37 UTC, merged