v1-add-store-test
training-of-new-employees/qon pull request #68
Opened 2023-12-22 13:57 UTC by kozyrev-m

1. Добавлен test-suite для тестирования слоя store

2023-12-23 13:33 UTC, Nexadis commented
Посмотрю, как пройдет линтеровские проверки

2023-12-25 05:29 UTC, Nexadis requested changes

2023-12-25 05:29 UTC, Nexadis commented on Makefile
> +	@for file in $^; do mockgen -source=$$file -destination=$(MOCKS_DESTINATION)/`echo $${file#*internal/}`; done
можешь объяснить что это значит?

2023-12-25 05:29 UTC, Nexadis commented on internal/store/pg/company_storage.go
> +	tx, err := c.db.Beginx()
Может это всё завернем в транзакции как в userStorage, так легче будет читать и функции будут не такими громоздкими

2023-12-25 05:29 UTC, Nexadis commented on internal/store/pg/company_storage_test.go
> +func (suite *storeTestSuite) TestCreateCompany() {
Думаю следует добавить кириллицу и тесты на наличие недопустимых символов согласно ТЗ:

Любые символы, латиница, кириллица, пробел, тире.
Длина не менее 1 и не более 256 символов.
Не принимает символы: ‘*’, ‘#’.
Не принимает Плохие Символы.

2023-12-25 05:29 UTC, Nexadis commented on internal/store/pg/position_storage.go
> +	tx, err := p.db.Beginx()
Также можно сделать внешнюю функцию которая сама будет создавать и отрабатывать транзакцию, а тут уже передавать в неё замыкание внутри которого работать с транзакцией

2023-12-25 05:29 UTC, Nexadis commented on internal/store/pg/user_storage.go
> +	tx, err := u.db.Beginx()
Тоже можно обернуть в транзакцию

2023-12-25 07:54 UTC, kozyrev-m commented on Makefile
> +	@for file in $^; do mockgen -source=$$file -destination=$(MOCKS_DESTINATION)/`echo $${file#*internal/}`; done
Почему-то у меня не работает подиструкция `echo $${file/internal/`.
Как понимаю, она должна убирать часть 'internal/' из пути файла. 
А вот так `echo $${file#*internal/`  - у меня работает.
Наверное, нужно сделать инструкцию универсалной для всех машин.

2023-12-25 08:07 UTC, kozyrev-m commented on internal/store/pg/company_storage_test.go
> +func (suite *storeTestSuite) TestCreateCompany() {
Эти проверки выполняются на верхнем уровне в валидациях.
В БД пока нет ограничений  с такими проверками (contraints), поэтому проверять эти кейсы на уровне store пока нет смысла.

2023-12-25 08:08 UTC, kozyrev-m commented on internal/store/pg/company_storage.go
> +	tx, err := c.db.Beginx()
По-моему, функция-обёртка tx() с одной стороны решает проблему дублирования кода, с другой усложняет восприятие кода.

2023-12-25 08:09 UTC, kozyrev-m commented on internal/store/pg/position_storage.go
> +	tx, err := p.db.Beginx()
По-моему, функция-обёртка tx() с одной стороны решает проблему дублирования кода, с другой усложняет восприятие кода.

2023-12-25 09:09 UTC, kozyrev-m commented on internal/store/pg/position_storage.go
> +	tx, err := p.db.Beginx()
Порефакторил

2023-12-25 09:09 UTC, kozyrev-m commented on internal/store/pg/company_storage.go
> +	tx, err := c.db.Beginx()
Порефакторил

2023-12-25 09:12 UTC, kozyrev-m commented on internal/store/pg/user_storage.go
> +	tx, err := u.db.Beginx()
Здесь лучше перенести в tx() потом, в следующем PR, когда будем покрывать тестами репозитрий user.

2023-12-25 14:22 UTC, Nexadis commented on internal/store/pg/company_storage_test.go
> +func (suite *storeTestSuite) TestCreateCompany() {
Согласен

2023-12-25 14:22 UTC, Nexadis commented on Makefile
> +	@for file in $^; do mockgen -source=$$file -destination=$(MOCKS_DESTINATION)/`echo $${file#*internal/}`; done
Ок

2023-12-25 14:24 UTC, Nexadis approved these changes

2023-12-25 15:23 UTC, Nexadis commented on internal/store/pg/position_storage.go
> +	return &positionStorage{db: db, store: s}
Не понял зачем зависимость Store

2023-12-25 15:34 UTC, kozyrev-m commented on internal/store/pg/position_storage.go
> +	return &positionStorage{db: db, store: s}
В store у нас работа с сущностями выполняется через репозитории: uStorage, companyStorage, positionStorage.

Чтобы получить доступ к методам соседних репозиториев, в каждый было добавлено поле store.

Например, в репозитории uStorage, при создании админа сначало выполняется создание компании, потом создание должности.
Эти методы относятся к другим репозиториям (companyStorage, positionStorage).

2023-12-25 16:27 UTC, merged