v1-add-http-response
training-of-new-employees/qon pull request #75
Opened 2023-12-24 11:13 UTC by kozyrev-m

1. Добавлен механизм преобразования ошибок приложения в http-ответ.

2023-12-24 11:53 UTC, Nexadis requested changes

2023-12-24 11:53 UTC, Nexadis commented on internal/app/rest/errs.go
> +	httpCode, exists := errorToCode[err.Error()]
Для всех обёрнутых ошибок не будет работать, а мы стараемся их оборачивать, для начала надо делать unwrapping

2023-12-24 11:53 UTC, Nexadis commented on internal/app/rest/errs.go
> +	errs.ErrOnlyAdmin.Error():     http.StatusMethodNotAllowed,
В таких ситуациях мы обычно возвращали `http.StatusForbidden`, мб просто не совсем понимаю зачем эта ошибка нужна

2023-12-24 11:53 UTC, Nexadis commented on internal/app/rest/errs.go
> +	c.JSON(httpCode, errResponse{Code: httpCode, Message: err.Error()})
Не понимаю зачем возвращать код, если он и так присутствует в заголовке?

2023-12-24 14:30 UTC, kozyrev-m commented on internal/app/rest/errs.go
> +	c.JSON(httpCode, errResponse{Code: httpCode, Message: err.Error()})
Такой формат тела ответа обсуждали PM с QA. Поэтому предварительно сделал так.
Формат не сложно будет поменять.

2023-12-24 14:32 UTC, kozyrev-m commented on internal/app/rest/errs.go
> +	errs.ErrOnlyAdmin.Error():     http.StatusMethodNotAllowed,
Да, ошибки и коды тоже нужно согласовывать.
Сейчас описанием ошибок занимается Владимир.

2023-12-24 14:33 UTC, kozyrev-m commented on internal/app/rest/errs.go
> +	httpCode, exists := errorToCode[err.Error()]
Не совсем понял.
Что нужно поправить?

2023-12-24 14:37 UTC, Nexadis commented on internal/app/rest/errs.go
> +	c.JSON(httpCode, errResponse{Code: httpCode, Message: err.Error()})
Ок, понял

2023-12-25 05:32 UTC, Nexadis approved these changes

2023-12-25 16:35 UTC, merged