V1 register employee
training-of-new-employees/qon pull request #8
Opened 2023-12-08 16:47 UTC by kozyrev-m

2023-12-08 16:57 UTC, rktkov requested changes
Вижу, что ПР создан на основании ветки, которая сама была создана от мейна с уже существующим кодом. Из-за этого мне тяжело проверить всю и дать комментарии на всю структуру проекта, потому что тут я вижу только 2 коммита. 
Исправте мои текущии комментарии, сделайте мерж, а потом пинганите меня в сообщениях, чтобы я зашел в репу и мейн ветку посмотрел всю.

2023-12-08 16:57 UTC, rktkov commented on internal/store/pg/user_storage.go
> +func (u *uStorage) UpdateUserPassword(ctx context.Context, email string, password string) error {
Такие вещи лучше выполнять завернутыми в транзакции.

2023-12-08 16:57 UTC, rktkov commented on internal/model/utils.go
> +package model
Лучше создать отдельный пакет utils на уровне internal и туда добавить подпакет  crypt

2023-12-08 16:57 UTC, rktkov commented on internal/app/rest/user_handler.go
> +	if err := r.services.User().UpdatePassword(ctx, userReq.Email, userReq.Password); err != nil {
Не понял логику, зачем в signin появляется обновление пароля?

2023-12-09 14:00 UTC, Nexadis approved these changes

2023-12-09 14:05 UTC, Nexadis approved these changes

2023-12-09 14:52 UTC, kozyrev-m commented on internal/app/rest/user_handler.go
> +	if err := r.services.User().UpdatePassword(ctx, userReq.Email, userReq.Password); err != nil {
Это хендлер для установки пароля и активации учётной записи сотрудника.
[Подробнее](https://github.com/orgs/training-of-new-employees/projects/1/views/6?pane=issue&itemId=47034719)

2023-12-09 16:27 UTC, rktkov approved these changes

2023-12-09 16:45 UTC, merged