V1 courses
training-of-new-employees/qon pull request #86
Opened 2024-01-10 05:46 UTC by Nexadis

2024-01-10 09:19 UTC, kozyrev-m requested changes

2024-01-10 09:19 UTC, kozyrev-m commented on internal/store/pg/course_storage.go
> +func (c *courseStorage) CreateCourse(ctx context.Context, course model.CourseSet) (model.Course, error) {
Может, лучше возвращать из метода указатель на структуру model.Course, как это делается в других репозиториях?
Это сохранит единообразие и позволит возвращать nil вместо пустой структуры.

Аналогично для других случаев ниже.

2024-01-10 09:19 UTC, kozyrev-m commented on internal/service/impl/course_service.go
> +func (cs *courseService) CreateCourse(ctx context.Context, c model.CourseSet) (model.Course, error) {
Думаю, что возвращение указателя на структуру может быть более удачным решением, так как это позволяет возвращать nil в случае, если данные не были успешно получены.
Это может быть полезно в случаях, когда требуется проверить наличие данных перед их использованием, и может помочь избежать непредвиденных ошибок в коде.

Аналогично в других методах.

2024-01-11 05:09 UTC, Nexadis commented on mocks/pkg/doar/doar.go
Эти файлы не пустые, просто тут показывает, что есть изменения в одной строке пустой

2024-01-11 05:50 UTC, Nexadis commented on internal/service/impl/course_service.go
> +func (cs *courseService) CreateCourse(ctx context.Context, c model.CourseSet) (model.Course, error) {
Зачем проверять наличие данных, если возникла ошибка? По сути индикатором того, что есть данные является отсутсвие ошибки.

2024-01-11 09:42 UTC, kozyrev-m commented on internal/store/pg/course_storage.go
> +func (c *courseStorage) CreateCourse(ctx context.Context, course model.CourseSet) (model.Course, error) {
Если посмотреть другие репозитории, у нас как-то само собой сложилось, что мы возвращаем nil из методов при ошибке.

По-хорошему, чтобы исключить подобную несогласованность в коде между разработчиками, изначально нужно было точно определить, что мы возвращаем из метода при ошибке: либо nil, либо пустую структуру, — и задокументировать это как правило.

В настоящий момент вопрос, конечно же, не принципиальный. У нас нет жесткого правила.
 
Если исправление не вызовет много трудностей, то для сохранениея единообразия лучше бы исправить возврат на nil.

2024-01-11 09:56 UTC, kozyrev-m commented on internal/service/impl/course_service.go
> +func (cs *courseService) CreateCourse(ctx context.Context, c model.CourseSet) (model.Course, error) {
Это да, проверять наличие данных при возникновении ошибки не всегда необходимо.

Однако, бывают случаи когда проще просто проверить наличие данных, а не анализировать содержание ошибки.
Например, при тестировании.

2024-01-11 10:26 UTC, kozyrev-m requested changes

2024-01-11 10:26 UTC, kozyrev-m commented on internal/store/pg/course_storage.go
> +	WHERE p.company_id = $1`
Этот запрос возвращает только назначенные на должности курсы компании.

Однако хендлер, использующий этот запрос, должен получить все курсы компании.
Поскольку у нас нет признака компании для курсов, мы можем при выборке оттолкнуться от создателя курса (created_by).

2024-01-11 12:13 UTC, Nexadis commented on internal/service/impl/course_service.go
> +func (cs *courseService) CreateCourse(ctx context.Context, c model.CourseSet) (model.Course, error) {
ОК, я поправлю для единообразия

2024-01-11 12:19 UTC, Nexadis commented on internal/store/pg/course_storage.go
> +	WHERE p.company_id = $1`
Отталкиваться от created_by тоже не получится, если несколько админов в компании. Может лучше взять всех админов в компании, и получить все курсы, у которых админы записаны в created_by?

2024-01-11 12:44 UTC, kozyrev-m commented on internal/store/pg/course_storage.go
> +	WHERE p.company_id = $1`
Да, можно так.
Также ещё можно добавить поле company_id в таблицу courses.

2024-01-11 13:30 UTC, kozyrev-m requested changes

2024-01-11 13:30 UTC, kozyrev-m commented on internal/service/impl/course_service.go
> +func (cs *courseService) CreateCourse(ctx context.Context, c model.CourseSet) (model.Course, error) {
В случае возврата массива можно оставить как есть (возвращать []model.Course)

2024-01-12 11:12 UTC, kozyrev-m requested changes
Не вижу тесты к хендлерам.

Еще один момент: давайте тестировать сервисы также с помощью тестового набора, как это делается в обработчиках и хранилище.

2024-01-12 11:33 UTC, kozyrev-m requested changes
Не вижу тестов к курсам для слоя хранилища

2024-01-15 12:22 UTC, Nexadis commented
Написал тесты для rest и store слоя в testsuite'ах

2024-01-15 15:31 UTC, kozyrev-m approved these changes

2024-01-15 16:23 UTC, merged